### ISSUE TITLE
External Video Walking Through Quickstart

### ISSUE THREAD

**Issue by hashedtitan** [Fairblock/ArbitrumContracts#6]
# TODO

A short video walking through the quickstart to be embedded into the README and in the docs. This may be replaced by the tutorial recording from DevCon 2024.

## Video
- [ ] Intro to tutorial should include a pre-amble on the stylus contracts:
   - What they do
   - How to deploy them
- [ ] Show a deployment of them
- [ ] Walk through the smart contract for integrating with it
- [ ] Walk through the test file for it
